query ugcArticleSolutionArticles($questionSlug: String!, $orderBy: ArticleOrderByEnum, $userInput: String, $tagSlugs: [String!], $skip: Int, $first: Int) {
    ugcArticleSolutionArticles(questionSlug: $questionSlug, orderBy: $orderBy, userInput: $userInput, tagSlugs: $tagSlugs, skip: $skip, first: $first) {
        totalNum
        pageInfo {
            hasNextPage
        }
        edges {
            node {
                title
                slug
                summary
                topicId
                tags {
                    name
                }
            }
        }
    }
}
