# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
  push:
    tags:
      - 'v*.*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set LD_VERSION
      if: ${{ github.event_name == 'push'}}
      run: echo "LD_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    - name: Set LD_VERSION
      if: ${{ github.event_name == 'workflow_dispatch'}}
      run: echo "LD_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
    - name: Set GITHUB_TOKEN
      run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV


    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '8' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
           ./gradlew clean
           ./gradlew build
      env:
        LD_VERSION: ${{ env.LD_VERSION }}

    - name: Publish to GitHub Packages
      run: |
           ./gradlew clean
           ./gradlew publish
      env:
        LD_VERSION: ${{ env.LD_VERSION }}
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ env.GITHUB_TOKEN }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: lc-sdk
        path: build/libs/lc-sdk-*.*.*.jar
